### ISSUE TITLE
你好，为啥报错c10:error

### ISSUE THREAD

**Issue by geegao** [ncdhz/Yolo-LibTorch#16]
在
`inline c10::intrusive_ptr<ivalue::Tuple> IValue::toTuple() && {
  AT_ASSERT(isTuple(), "Expected Tuple but got ", tagKind());
  return moveToIntrusivePtr<ivalue::Tuple>();`
报错：0x00007FFA5F0FCD29 处(位于 kuka_socket_new_1.exe 中)有未经处理的异常: Microsoft C++ 异常: c10::Error，位于内存位置 0x000000A1EE6FF160 处。

**Comment by geegao** [comment]
好像是totensor的问题，我看其他博客上因为模型输出需要改成tolist，但是改了之后non_max_suppression的参数数据类型就不正确了

**Comment by ncdhz** [comment]
@geegao 也可以检查一下是不是环境没有配好。

**Comment by geegao** [comment]
环境检查了，没有问题，就是正常配置的libtorch

**Comment by ncdhz** [comment]
@geegao 如果使用到cuda可以把变量放入cuda测试一下。还有就是debug和release版本得注意一下。
