### ISSUE TITLE
讀取pt時報錯

### ISSUE THREAD

**Issue by star70531** [ncdhz/Yolo-LibTorch#19]
您好，麻煩一下
利用cpu運行時沒問題
使用gpu運行至讀取pt檔的時候發生以下報錯(有使用gpu進行export torchscript檔案)

0x00007FFA55ECCF19 中 (於 Libtorch_yolov5_DLLtest.exe) 發生未處理的例外狀況: Microsoft C++ 發生例外狀況: c10::NotImplementedError (記憶體位置 0x000000C0766F9530)。

此報錯發生在OperatorEntry.h底下的
const KernelFunction& lookup(DispatchKey k) const {
    const auto& kernel = dispatchTable_[static_cast<uint8_t>(k)];
    // A valid kernel *always* has a boxed kernel and *may* have an
    // unboxed kernel. However, we typically do unboxed calls in at::
    // APIs, where the kernel 1) will very likely be valid and 2)
    // should have an unboxed kernel. Checking the unboxed kernel
    // first will allow us to avoid touching the boxed kernel at all
    // in the common case.
    if (C10_UNLIKELY(!kernel.isValidUnboxed())) {
      if (!kernel.isValid()) {
        reportError(k);
      }
    }
    return kernel;
  }

想請問這是甚麼問題，謝謝

**Comment by ncdhz** [comment]
你可以验证一下能否在Libtorch种使用Cuda https://zhuanlan.zhihu.com/p/375084412

**Comment by star70531** [comment]
> 你可以验证一下能否在Libtorch中使用Cuda https://zhuanlan.zhihu.com/p/375084412

@ncdhz 
有cout<<torch::cuda::is_available() 
確認cuda可用

**Comment by star70531** [comment]
> 你可以验证一下能否在Libtorch中使用Cuda https://zhuanlan.zhihu.com/p/375084412

@ncdhz 
libtorch版本為1.10.0
cuda為11.3
同時程式中已輸出確認cuda是否可用並有回傳1
試了很久還是不知道什麼問題
麻煩了，謝謝

**Comment by ncdhz** [comment]
@star70531 
```cpp
#include <torch/torch.h>
#include <iostream>
int main() {
	torch::Tensor tensor = torch::rand({ 2, 3 });
	if (torch::cuda::is_available()) {
		std::cout << "CUDA is available! Training on GPU" << std::endl;
		auto tensor_cuda = tensor.cuda();
		std::cout << tensor_cuda << std::endl;
	}
	else
	{
		std::cout << "CUDA is not available! Training on CPU" << std::endl;
		std::cout << tensor << std::endl;
	}

	std::cin.get();
}
```
可以通过上面代码继续验证cuda是否配置成功。
如果配置成功可以尝试统一导出`torchscript`文件的`pytorch`版本与`libtorch`的版本。使用`gpu`必须导出`cuda`版本模型。
如果任然不成功你可以把你详细的配置步骤发出来。

**Comment by star70531** [comment]
> @star70531
> 
> ```c++
> #include <torch/torch.h>
> #include <iostream>
> int main() {
> 	torch::Tensor tensor = torch::rand({ 2, 3 });
> 	if (torch::cuda::is_available()) {
> 		std::cout << "CUDA is available! Training on GPU" << std::endl;
> 		auto tensor_cuda = tensor.cuda();
> 		std::cout << tensor_cuda << std::endl;
> 	}
> 	else
> 	{
> 		std::cout << "CUDA is not available! Training on CPU" << std::endl;
> 		std::cout << tensor << std::endl;
> 	}
> 
> 	std::cin.get();
> }
> ```
> 
> 可以通过上面代码继续验证cuda是否配置成功。 如果配置成功可以尝试统一导出`torchscript`文件的`pytorch`版本与`libtorch`的版本。使用`gpu`必须导出`cuda`版本模型。 如果仍然不成功你可以把你详细的配置步骤发出来。

@ncdhz 您好
上面代碼執行後，有產生CUDA is available! Training on GPU的字樣
但顯示那行之後就會跳到那個c10::NotImplementedError的錯誤

**Comment by ncdhz** [comment]
@star70531 你的`libtorch`版本和`cuda`版本是否匹配，如果匹配可以仔细参考<https://zhuanlan.zhihu.com/p/375084412>进行配置，如果不匹配需要更换`libtorch`版本。

**Comment by star70531** [comment]
@ncdhz 
剛查看了一下，透過nvcc -V 查看CUDA版本為11.3
libtorch裡的build-version裡顯示為1.10.0+cu113
VS2019裡的配置也與文章相同

**Comment by ncdhz** [comment]
@star70531 可以把你的相关配置发出来

**Comment by star70531** [comment]
> @star70531 可以把你的相关配置发出来

@ncdhz 您好
我剛剛測試成功了
原因出在於字符串那串
我將每個字串都輪流加上去測試看看結果可以了

感謝您的幫忙
