### ISSUE TITLE
你好，这个代码已经可以部署yolov8了吗，对libtorch和opencv版本有要求吗？

### ISSUE THREAD

**Issue by jiqiang2022** [ncdhz/Yolo-LibTorch#20]

**Comment by ncdhz** [comment]
@jiqiang2022 可以了 [ncdhz.github.io/Yolo-LibTorch](https://ncdhz.github.io/Yolo-LibTorch) 这是文档（还有部分文档有待完善）。对`libtorch`和`opencv`没有特殊要求，只需要能正常在电脑中运行就好，如`libtorch`和`cuda`的对应关系。

**Comment by jiqiang2022** [comment]
那这个代码可以实现YOLOv8的分割任务吗

**Comment by ncdhz** [comment]
@jiqiang2022 不能

**Comment by jiqiang2022** [comment]
> @jiqiang2022 不能

那我需要这个分割任务，在你这个代码的基础上作修改容易吗，图片的预处理部分是一样的吗？

**Comment by ncdhz** [comment]
应该也不难，预测部分需要改，然后对模型返回的结果需要处理一下。

**Comment by WuJieLuen** [comment]
感謝大大!
