### ISSUE TITLE
yolov8和yolov5区别

### ISSUE THREAD

**Issue by Ellohiye** [ncdhz/Yolo-LibTorch#23]
作者您好，我在导出torchscript格式的文件时，发现Yolov8和yolov5在第三维（代表各种属性信息）少了一行。 Yolov8 导出尺寸（1、10、8400）； 而 yolov5 导出尺寸 (1 ,11,XXX)。 我的数据包含五个类别。 缺失的一行数据代表什么呢？我把您代码中关于Yolov8的处理转移到我的代码中，但是发现不能检测最后一类缺陷。

**Comment by ncdhz** [comment]
@Ellohiye 缺少一行数据为置信度，YoloV8中采用类别中最大的概率作为置信度。

**Comment by Ellohiye** [comment]
> @Ellohiye 缺少一行数据为置信度，YoloV8中采用类别中最大的概率作为置信度。

作者您好，按道理来说C++的推理速度应该要比python快，但是实际发现集成到C++中检测一张图片需要几十毫秒，但是python中检测一张图片只需10ms左右，请问您知道这是怎么回事吗

**Comment by ncdhz** [comment]
@Ellohiye 这个可能和模型格式有关吧，你可以测试一下`TorchScript`格式模型，在`Python`中需要多少时间。

**Comment by Ellohiye** [comment]
> @Ellohiye 这个可能和模型格式有关吧，你可以测试一下`TorchScript`格式模型，在`Python`中需要多少时间。

但是话说`TorchScript`格式模型推出来的目的不是为了加快推理速度以及促进多平台部署吗？

**Comment by ncdhz** [comment]
@Ellohiye 是为了多平台部署。但是，是不是加快了推理速度不好说。

**Comment by ncdhz** [comment]
@Ellohiye 是为了多平台部署。但是，是不是加快了推理速度不好说。
