### ISSUE TITLE
为什么会有这些报错信息

### ISSUE THREAD

**Issue by superGrandpaxx** [ncdhz/Yolo-LibTorch#25]
C:\devResources\gitproject\Yolo-LibTorch-main\Yolo-LibTorch-main\src\Yolo.cpp(11,8): error C2039: "device": 不是 "Yolo" 的
成员 [C:\devResources\gitproject\Yolo-LibTorch-main\Yolo-LibTorch-main\build\src\Yolo.vcxproj]
  C:\devResources\gitproject\Yolo-LibTorch-main\Yolo-LibTorch-main\include\Yolo.h(53,7):
  参见“Yolo”的声明

C:\devResources\gitproject\Yolo-LibTorch-main\Yolo-LibTorch-main\src\Yolo.cpp(15,8): error C2039: "confThres": 不是 "Yolo
" 的成员 [C:\devResources\gitproject\Yolo-LibTorch-main\Yolo-LibTorch-main\build\src\Yolo.vcxproj]
  C:\devResources\gitproject\Yolo-LibTorch-main\Yolo-LibTorch-main\include\Yolo.h(53,7):
  参见“Yolo”的声明

C:\devResources\gitproject\Yolo-LibTorch-main\Yolo-LibTorch-main\src\Yolo.cpp(16,8): error C2039: "isHalf": 不是 "Yolo" 的
成员 [C:\devResources\gitproject\Yolo-LibTorch-main\Yolo-LibTorch-main\build\src\Yolo.vcxproj]
  C:\devResources\gitproject\Yolo-LibTorch-main\Yolo-LibTorch-main\include\Yolo.h(53,7):
  参见“Yolo”的声明

C:\devResources\gitproject\Yolo-LibTorch-main\Yolo-LibTorch-main\src\Yolo.cpp(23,34): error C2039: "non_max_suppression
": 不是 "Yolo" 的成员 [C:\devResources\gitproject\Yolo-LibTorch-main\Yolo-LibTorch-main\build\src\Yolo.vcxproj]
  C:\devResources\gitproject\Yolo-LibTorch-main\Yolo-LibTorch-main\include\Yolo.h(53,7):
  参见“Yolo”的声明

C:\devResources\gitproject\Yolo-LibTorch-main\Yolo-LibTorch-main\src\Yolo.cpp(40,23): error C3861: “xywh2xyxy”: 找不到标识符
[C:\devResources\gitproject\Yolo-LibTorch-main\Yolo-LibTorch-main\build\src\Yolo.vcxproj]
C:\devResources\gitproject\Yolo-LibTorch-main\Yolo-LibTorch-main\src\Yolo.cpp(55,22): error C3861: “nms”: 找不到标识符 [C:\de
vResources\gitproject\Yolo-LibTorch-main\Yolo-LibTorch-main\build\src\Yolo.vcxproj]
C:\devResources\gitproject\Yolo-LibTorch-main\Yolo-LibTorch-main\src\Yolo.cpp(61,18): error C2039: "getRandScalar": 不是

"Yolo" 的成员 [C:\devResources\gitproject\Yolo-LibTorch-main\Yolo-LibTorch-main\build\src\Yolo.vcxproj]
  C:\devResources\gitproject\Yolo-LibTorch-main\Yolo-LibTorch-main\include\Yolo.h(53,7):
  参见“Yolo”的声明

**Comment by superGrandpaxx** [comment]
兄弟们我终于搞定了，设能想到
解决方法：代码中所有//单行注释的地方如果这个注释是中文，要与下一行代码隔一行，就是不能挨着，真的坑

**Comment by ncdhz** [comment]
@superGrandpaxx 还可以删除所有中文注释，至于为什么有的机器可以运行，有的机器需要删除中文注释，我怀疑和编码有关系。
