### ISSUE TITLE
用自己训练出来的yolo8的推理，程序崩溃；用您给出来的yolov8n.cuda.torchscript可以正常出结果

### ISSUE THREAD

**Issue by moheikanshu** [ncdhz/Yolo-LibTorch#26]
为什么在我用自己训练出的person.torchscript运行到下面
if (strcmp(this->version.c_str(), V8) == 0)
	{
	// 处理V8版本的预测结果
		torch::Tensor pT = pred.toTensor();
		torch::Tensor score = std::get<0>(pT.slice(1, 4, -1).max(1, true));
		data = torch::cat({pT.slice(1, 0, 4), score, pT.slice(1, 4, -1)}, 1).permute({0, 2, 1});
	} 会崩溃呢？

**Comment by moheikanshu** [comment]
@ncdhz 麻烦大佬了，我遇到这个问题卡住了。这是运行您仓库里自带的torchsrcipt输出正常
![9ab8a248ec8feb69ee2b2164dacbf06](https://github.com/ncdhz/Yolo-LibTorch/assets/73371148/9f443175-1ae0-42cd-a293-ef80fa4d3440)
用我自己训练的就报错了
![3d8888935ea12b0a6057d6c2a1c424d](https://github.com/ncdhz/Yolo-LibTorch/assets/73371148/25e3ad6d-6971-471e-963a-c4fd3b383c01)
下面是我代码的一部分截图，麻烦您了，万分感谢！！
![f3d23b654cca01e9172255cec710da7](https://github.com/ncdhz/Yolo-LibTorch/assets/73371148/b1d12866-ee39-4aeb-9007-74677cc3d9df)
这里头切片一直是空的

**Comment by ncdhz** [comment]
@moheikanshu 图片输入维度是多少

**Comment by moheikanshu** [comment]
宽和高都是320，通道是16，感觉是这个原因呢，非常感谢大佬耐心回复



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月23日(星期二) 上午9:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ncdhz/Yolo-LibTorch] 用自己训练出来的yolo8的推理，程序崩溃；用您给出来的yolov8n.cuda.torchscript可以正常出结果 (Issue #26)





 
@moheikanshu 图片输入维度是多少

**Comment by ncdhz** [comment]
@moheikanshu 加油

**Comment by moheikanshu** [comment]
@ncdhz 大佬，我这里除了您自带的两个yolo8的可以运行，我自己训练的yolo5的可以运行，其他一直会报错的，还是那些错误，然后yolo5的推理速度有点慢，我实在nvidia jetson xavier nx上跑的

**Comment by ncdhz** [comment]
@moheikanshu 我不知道你模型导出有没有问题，可以参考<https://ncdhz.github.io/Yolo-LibTorch/#/./export>，如果模型导出没有问题，可以设定一下模型输入的图片高宽，本项目默认使用的是`640*640`。至于速度，你可以选择小一点的模型，或者小一点的图片。图片尺寸应与导出模型尺寸一致。

**Comment by moheikanshu** [comment]
非常感谢老了！我先看看这个文档，然后再尝试训练下，看看训练出来的v8.torchsrcipt能不能正常的在我的jetson上跑起来，现在v5是可以跑起来，就是推理时间比较久




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ncdhz/Yolo-LibTorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月26日(星期五) 中午1:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ncdhz/Yolo-LibTorch] 用自己训练出来的yolo8的推理，程序崩溃；用您给出来的yolov8n.cuda.torchscript可以正常出结果 (Issue #26)





 
@moheikanshu 我不知道你模型导出有没有问题，可以参考https://ncdhz.github.io/Yolo-LibTorch/#/./export，如果模型导出没有问题，可以设定一下模型输入的图片高宽，本项目默认使用的是640*640。至于速度，你可以选择小一点的模型，或者小一点的图片。图片尺寸应与导出模型尺寸一致。

**Comment by moheikanshu** [comment]
大佬您好，有微信方便联系吗？（有偿请教大佬点问题），我训练了几种模型，都是v8n的，我添加到付件里，云行的时候会报错，v5的模型在nvidia jetson xavier nx上跑的时候，推理比较慢，您自带的v8模型，推理很快，但是识别不准，我把我的类别文件和权重文件都上传，麻烦您了




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "ncdhz/Yolo-LibTorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月26日(星期五) 中午1:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ncdhz/Yolo-LibTorch] 用自己训练出来的yolo8的推理，程序崩溃；用您给出来的yolov8n.cuda.torchscript可以正常出结果 (Issue #26)





 
@moheikanshu 我不知道你模型导出有没有问题，可以参考https://ncdhz.github.io/Yolo-LibTorch/#/./export，如果模型导出没有问题，可以设定一下模型输入的图片高宽，本项目默认使用的是640*640。至于速度，你可以选择小一点的模型，或者小一点的图片。图片尺寸应与导出模型尺寸一致。

**Comment by ncdhz** [comment]
@moheikanshu 我主页<https://github.com/ncdhz>的手机号就是我的微信号。
