### ISSUE TITLE
大佬、你的libtorch是哪个版本呢？

### ISSUE THREAD

**Issue by ZhangAdjy** [ncdhz/Yolo-LibTorch#27]
我用的是1.12.1版本，在torch::jit::load时会崩溃，不知道是不是版本的原因？

**Comment by ncdhz** [comment]
@ZhangAdjy 应该不是版本问题（我测试过好几个版本都可以），可能是libtorch的环境没有配置好。

**Comment by ZhangAdjy** [comment]
谢谢大佬回复，应该就是版本和你提供的模型版本不匹配，我更新成2.0.1后，就可以了








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年4月17日(周三) 晚上10:40写道:

  

 
@ZhangAdjy 应该不是版本问题（我测试过好几个版本都可以），可能是libtorch的环境没有配置好。

**Comment by ncdhz** [comment]
@ZhangAdjy 能够运行就好

**Comment by ZhangAdjy** [comment]
大佬，我再请教一个问题，libtorch能做到和pytorch一样的推理精度吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月17日(周三) 晚上11:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ncdhz/Yolo-LibTorch] 大佬、你的libtorch是哪个版本呢？ (Issue #27)




 
@ZhangAdjy 能够运行就好

**Comment by ncdhz** [comment]
@ZhangAdjy 对于YOLO这个模型，精度应该是一样的，只要模型里面没有判断，精度就一致。

**Comment by TerryLoveMl** [comment]
> @ZhangAdjy 对于YOLO这个模型，精度应该是一样的，只要模型里面没有判断，精度就一致。

非常感谢开源，收益良多！我目前使用yolov8作推理，相比python推理的精度下降很多，没有改动模型架构，能帮忙分析分析原因吗

**Comment by ZhangAdjy** [comment]
我目前也是下降很多，感觉就是框架本身的问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月3日(周五) 下午4:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ncdhz/Yolo-LibTorch] 大佬、你的libtorch是哪个版本呢？ (Issue #27)




  
@ZhangAdjy 对于YOLO这个模型，精度应该是一样的，只要模型里面没有判断，精度就一致。
  
非常感谢开源，收益良多！我目前使用yolov8作推理，相比python推理的精度下降很多，没有改动模型架构，能帮忙分析分析原因吗

**Comment by ncdhz** [comment]
@TerryLoveMl @ZhangAdjy 方便的话，可以把你们的模型和图片发我，我可以研究一下。

**Comment by TerryLoveMl** [comment]
> @TerryLoveMl @ZhangAdjy 方便的话，可以把你们的模型和图片发我，我可以研究一下。
大佬，由于文件过大，通过邮箱发你了，请帮忙分析分析，非常感谢~

**Comment by ncdhz** [comment]
@TerryLoveMl 这应该是一个`BUG`我尽快抽时间解决一下

**Comment by ZhangAdjy** [comment]
大佬，实在不好意思哈，由于是公司的模型，我没办法发出来，抱歉








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年5月6日(周一) 上午9:28写道:

  

 
@TerryLoveMl @ZhangAdjy 方便的话，可以把你们的模型和图片发我，我可以研究一下。

**Comment by ZhangAdjy** [comment]
谢谢大佬，烦请修复了bug通知一下








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年5月6日(周一) 下午2:39写道:

  

 
@TerryLoveMl 这应该是一个BUG我尽快抽时间解决一下

**Comment by ncdhz** [comment]
@ZhangAdjy 没事，已经定位到问题了，我尽快解决一下

**Comment by TerryLoveMl** [comment]
> @TerryLoveMl 这应该是一个`BUG`我尽快抽时间解决一下
期待更新~

**Comment by ncdhz** [comment]
@TerryLoveMl @ZhangAdjy `BUG`已经修复，你们可以尝试一下。

**Comment by ZhangAdjy** [comment]
好的，大佬厉害👍🏻，我去验证一下








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年5月10日(周五) 中午11:42写道:

  

 
@TerryLoveMl @ZhangAdjy BUG已经修复，你们可以尝试一下。

**Comment by ZhangAdjy** [comment]
大佬，我测试了，pytorch版本和libtorch版本都是2.0.1，结果还是不一样，但是差别比上个版本的小很多了。
pytorch:&nbsp; x1:302&nbsp; &nbsp;y1:284&nbsp; x2:583&nbsp; &nbsp;y2:764&nbsp; &nbsp;score:0.9456


libtorch:  x1:303&nbsp; &nbsp;y1:300&nbsp; &nbsp;x2:585&nbsp; &nbsp;y2:776 score:0.9451



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月10日(周五) 中午11:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ncdhz/Yolo-LibTorch] 大佬、你的libtorch是哪个版本呢？ (Issue #27)




 
@TerryLoveMl @ZhangAdjy BUG已经修复，你们可以尝试一下。

**Comment by ncdhz** [comment]
@ZhangAdjy 这个差距可能是读取图片的方式不同引起的，可以忽略不计。

**Comment by ZhangAdjy** [comment]
嗯嗯，虽然libtorch和pytorch都是按照opencv来读的，但不同的框架可能读出来也会有差别。我后续集成到软件里，识别的种类多了再看看效果差别大不大。谢谢大佬的帮助(#^.^#)🙏🏻



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月11日(周六) 中午1:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ncdhz/Yolo-LibTorch] 大佬、你的libtorch是哪个版本呢？ (Issue #27)




 
@ZhangAdjy 这个差距可能是读取图片的方式不同引起的，可以忽略不计。

**Comment by ZhangAdjy** [comment]
大佬，想请教一个问题，不知道您有没有在qtcreator下配置过libtorch？我配置好了环境，测试最基础的操作，只是#include <torch/torch.h&gt;，编译就会报很多错误。但在vs2017下就可以正常使用，查了很多文章，还没找到解决办法，特来请教一下








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ncdhz/Yolo-LibTorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月11日(星期六) 中午1:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ncdhz/Yolo-LibTorch] 大佬、你的libtorch是哪个版本呢？ (Issue #27)





 
@ZhangAdjy 这个差距可能是读取图片的方式不同引起的，可以忽略不计。

**Comment by ncdhz** [comment]
@ZhangAdjy 我没有在qtcreator下配置过libtorch，不太明白`在vs2017下就可以正常使用`是什么意思。

**Comment by ZhangAdjy** [comment]
已经解决了。开始的问题是在vs2017下配置libtorch项目可以正常编译，但在qtcreator下配置libtorch项目需要删除libtorch库中头文件的一些代码，不然编译就会报错








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年5月14日(周二) 晚上9:13写道:

  

 
@ZhangAdjy 我没有在qtcreator下配置过libtorch，不太明白在vs2017下就可以正常使用是什么意思。

**Comment by TerryLoveMl** [comment]
> @TerryLoveMl @ZhangAdjy `BUG`已经修复，你们可以尝试一下。
前几天在忙别的事情，今天已经验证过了，确实效果提升好多，赞👍
