### ISSUE TITLE
关于yolov5版本和精度问题

### ISSUE THREAD

**Issue by xiaowk5516** [ncdhz/Yolo-LibTorch#4]
您好，请问你这个项目针对yolov5的哪个版本呢？还是通用的？
另外一个问题是转换后的精度相比较yolov5有下降么？

**Comment by ncdhz** [comment]
@xiaowk5516 第一我也不知道 yolov5 现在官方代码更新到什么程度了，所以并不知道是不是所有版本都适用，至少十天前最新版本是可以用的，第二精度是否有所下降得看pytorch model 转换为 torchscript 模型时精度是否有变化（这里也希望您可以帮忙测试一下，谢谢）。

**Comment by xiaowk5516** [comment]
> @xiaowk5516 第一我也不知道 yolov5 现在官方代码更新到什么程度了，所以并不知道是不是所有版本都适用，至少十天前最新版本是可以用的，第二精度是否有所下降得看pytorch model 转换为 torchscript 模型时精度是否有变化（这里也希望您可以帮忙测试一下，谢谢）。

ok，我尽快试一下。

**Comment by xiaowk5516** [comment]
> @xiaowk5516 第一我也不知道 yolov5 现在官方代码更新到什么程度了，所以并不知道是不是所有版本都适用，至少十天前最新版本是可以用的，第二精度是否有所下降得看pytorch model 转换为 torchscript 模型时精度是否有变化（这里也希望您可以帮忙测试一下，谢谢）。

我在ubuntu18.04, 2080ti, libtorch1.8.1上测试的结果和python接近（10k+图片），精度应该没啥问题。
速度方面，由于是在服务器上测试，一直有人在用着，不能给出一个比较准确的结果。目前看来yolov5.5 l，速度在60~70fps，老实说是挺慢的。
你那边有推理速度的测试结果么？

**Comment by xiaowk5516** [comment]
> > @xiaowk5516 第一我也不知道 yolov5 现在官方代码更新到什么程度了，所以并不知道是不是所有版本都适用，至少十天前最新版本是可以用的，第二精度是否有所下降得看pytorch model 转换为 torchscript 模型时精度是否有变化（这里也希望您可以帮忙测试一下，谢谢）。
> 
> 我在ubuntu18.04, 2080ti, libtorch1.8.1上测试的结果和python接近（10k+图片），精度应该没啥问题。 速度方面，由于是在服务器上测试，一直有人在用着，不能给出一个比较准确的结果。目前看来yolov5.5 l，速度在60~70ms，老实说是挺慢的。 你那边有推理速度的测试结果么？

前处理耗时主要发生在
```
data = data.toType(torch::kFloat)
data = data.div(255);
``` 
这部分。resize，BGR->RGB耗时0~2ms。

推理部分耗时23~35ms，有点打不过pytorch啊

**Comment by ncdhz** [comment]
@xiaowk5516 谢谢您给的测试结果，由于写这个项目的时候我并不是一定要使用 yolov5 这个模型，我这边并没有做过详细的测试。可能是比直接使用 pytorch 慢一点（至于为什么慢我也没有深究），数据预处理方法可能存在过多的判断适应不同的情况而导致速度变慢了。不过我好像重载了一个直接传入 tensor 来预测的方法，可以试一下。

**Comment by xiaowk5516** [comment]
> @xiaowk5516 谢谢您给的测试结果，由于写这个项目的时候我并不是一定要使用 yolov5 这个模型，我这边并没有做过详细的测试。可能是比直接使用 pytorch 慢一点（至于为什么慢我也没有深究），数据预处理方法可能存在过多的判断适应不同的情况而导致速度变慢了。不过我好像重载了一个直接传入 tensor 来预测的方法，可以试一下。

ok，正在查找资料，看能不能提点速度。我看您之前有加过别人，不知道放不方便加一下我的联系方式，QQ:1263850500.
